apiVersion: v1
kind: ConfigMap
metadata:
  name: msvc-usuarios
data:
  lb_auth_issuer_uri: http://host.docker.internal:1034
  lb_usuarios_uri: http://host.docker.internal:1031
  port: "8001"
  db_host: mysql8:3306
  db_database: msvc_usuarios
#  username: root
#  password: sasa
  curso_url: msvc-cursos:8002
  application.yaml: |-
    config:
      texto: Configurando ambiente por defecto
    ---
    spring:
      config:
        activate:
          on-profile: dev
    config:
      texto: Configurando ambiente de desarrollo
    ---
    spring:
      config:
        activate:
          on-profile: prod
    config:
      texto: Configurando ambiente de produccion
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: msvc-cursos
data:
 port: "8002"
 db_host: postgres14:5432
 db_database: msvc_cursos
# username: postgres
# password: root
 usuario_url: msvc-usuarios:8001
