apiVersion: v1
kind: ConfigMap
metadata:
  name: msvc-usuarios
data:
  port: "8001"
  db_host: mysql8:3306
  db_database: msvc_usuarios
#  username: root
#  password: sasa
  curso_url: msvc-cursos:8002
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: msvc-cursos
data:
 port: "8002"
 db_host: postgres14:5432
 db_database: msvc_cursos
# username: postgres
# password: root
 usuario_url: msvc-usuarios:8001
